/**
 * Created by alexandru on 7/14/16.
 */
package jlg.jade.asterix.cat048;

import jlg.jade.asterix.AsterixItemLength;
import jlg.jade.asterix.FixedLengthAsterixData;

import java.util.BitSet;

/**
 * Cat048Item260 - ACAS Resolution Advisory Report
 * Currently active Resolution Advisory (RA), if any, generated by the
 * ACAS associated with the transponder transmitting the report and
 * threat identity data.
 */
public class Cat048Item260 extends FixedLengthAsterixData {
    private int threatTypeIndicator;            // TTI

    @Override
    protected int setSizeInBytes() {
        return AsterixItemLength.SEVEN_BYTES.getValue();
    }

    @Override
    protected void decodeFromByteArray(byte[] input, int offset) {
        BitSet bs = BitSet.valueOf(input);

        // TTI
        final int TTI_BIT1_INDEX = 62;
        final int TTI_BIT0_INDEX = 61;

        int TTIBit1Value = 0;
        int TTIBit0Value = 0;

        if (bs.get(TTI_BIT1_INDEX)) {
            TTIBit1Value = 1;
        }

        if (bs.get(TTI_BIT0_INDEX)) {
            TTIBit0Value = 1;
        }

        this.threatTypeIndicator = TTIBit1Value * 2 + TTIBit0Value;

        appendItemDebugMsg("TTI", this.threatTypeIndicator);
    }

    @Override
    protected String setDisplayName() {
        return "Cat048Item260 - ACAS Resolution Advisory Report";
    }

    public int getThreatTypeIndicator() {
        return threatTypeIndicator;
    }
}
